$schema: "http://json-schema.org/draft-07/schema#"
description: RAPIDS configuration schema
required:
  - DATABASE_GROUP
  - TIMEZONE
  - CREATE_PARTICIPANT_FILES
  - PHONE_CALLS
  - PHONE_KEYBOARD
  - PHONE_LOCATIONS

definitions:
  PROVIDER:
    type: object
    required: [COMPUTE, SRC_FOLDER, SRC_LANGUAGE, FEATURES]
    properties:
      COMPUTE:
        type: boolean
      FEATURES:
        type: [array, object]
      SRC_FOLDER:
        type: string
      SRC_LANGUAGE:
        type: string
        enum: [python, r]

  DORYAB_BLUETOOTH_FEATURE:
    type: object
    required: [DEVICES, SCANS_MOST_FREQUENT_DEVICE, SCANS_LEAST_FREQUENT_DEVICE]
    properties:
      DEVICES:
        type: array
        uniqueItems: True
        items:
          type: string
          enum: ["countscans", "uniquedevices", "meanscans", "stdscans"]
      SCANS_MOST_FREQUENT_DEVICE:
        type: array
        uniqueItems: True
        items:
          type: string
          enum: ["withinsegments", "acrosssegments", "acrossdataset"]
      SCANS_LEASE_FREQUENT_DEVICE:
        type: array
        uniqueItems: True
        items:
          type: string
          enum: ["withinsegments", "acrosssegments", "acrossdataset"]

    
  
properties:
  DATABASE_GROUP:
    type: string

  TIMEZONE:
    type: string
  
  CREATE_PARTICIPANT_FILES:
    type: object
    required: [SOURCE]
    properties:
      SOURCE:
        type: object
        required: [TYPE]
        properties:
          TYPE:
            type: string
            enum: [AWARE_DEVICE_TABLE, CSV_FILE]
          DATABASE_GROUP:
            type: string
          CSV_FILE_PATH:
            type: string
            pattern: "^.*\\.csv$"
          TIMEZONE:
            type: string
      PHONE_SECTION:
        type: object
        properties:
          ADD:
            type: boolean
          DEVICE_ID_COLUMN:
            type: string
          IGNORED_DEVICE_IDS:
            type: array
            items:
              type: string
      FITBIT_SECTION:
        properties:
          ADD:
            type: boolean
          DEVICE_ID_COLUMN:
            type: string
          IGNORED_DEVICE_IDS:
            type: array
            items:
              type: string

  PHONE_BLUETOOTH:
    type: object
    required: [TABLE, PROVIDERS]
    properties:
      TABLE:
        type: string
      PROVIDERS:
        properties:
          type: ["null", object]
          RAPIDS:
            allOf:
              - $ref: "#/definitions/PROVIDER"
              - properties:
                  FEATURES:
                    uniqueItems: True
                    items:
                      type: string
                      enum: ["countscans", "uniquedevices", "countscansmostuniquedevice"]
          DORYAB:
            allOf:
              - $ref: "#/definitions/PROVIDER"
              - properties:
                  FEATURES:
                    type: object
                    required: [ALL, OWN, OTHERS]
                    properties:
                      ALL: 
                        allOf:
                          - $ref: "#/definitions/DORYAB_BLUETOOTH_FEATURE"
                      OWN:
                        allOf:
                          - $ref: "#/definitions/DORYAB_BLUETOOTH_FEATURE"
                      OTHERS:
                        allOf:
                          - $ref: "#/definitions/DORYAB_BLUETOOTH_FEATURE"
        additionalProperties:
          $ref: "#/definitions/PROVIDER"

                      
  PHONE_CALLS:
    type: object
    required: [TABLE, PROVIDERS]
    properties:
      TABLE: 
        type: string
      PROVIDERS:
        type: ["null", object]
        properties:
          RAPIDS:
            allOf:
                - $ref: "#/definitions/PROVIDER"
                - properties:
                    CALL_TYPES:
                      type: array
                      items:
                        type: string
                        enum: [missed, incoming, outgoing]
                    FEATURES: 
                      type: object
                      required: [missed, incoming, outgoing]
                      properties:
                        missed:
                          type: array
                          uniqueItems: True
                          items:
                            type:
                              string
                            enum: [count, distinctcontacts, timefirstcall, timelastcall, countmostfrequentcontact]
                        incoming:
                          type: array
                          uniqueItems: True
                          items:
                            type:
                              string
                            enum: [count, distinctcontacts, meanduration, sumduration, minduration, maxduration, stdduration, modeduration, entropyduration, timefirstcall, timelastcall, countmostfrequentcontact]
                        outgoing:
                          type: array
                          uniqueItems: True
                          items:
                            type:
                              string
                            enum: [count, distinctcontacts, meanduration, sumduration, minduration, maxduration, stdduration, modeduration, entropyduration, timefirstcall, timelastcall, countmostfrequentcontact]
        additionalProperties:
          $ref: "#/definitions/PROVIDER"

  PHONE_CONVERSATION:
    type: object
    required: [TABLE, PROVIDERS]
    properties:
      TABLE:
        type: object
        required: [ANDROID, IOS]
        properties:
          ANDROID:
            type: string
          IOS:
            type: string
      PROVIDERS:
        type: ["null", object]
        properties:
          RAPIDS:
            allOf:
              - $ref: "#/definitions/PROVIDER"
              - properties:
                  FEATURES:
                    items:
                      type: string
                      enum: ["minutessilence", "minutesnoise", "minutesvoice", "minutesunknown","sumconversationduration","avgconversationduration",
    "sdconversationduration","minconversationduration","maxconversationduration","timefirstconversation","timelastconversation","noisesumenergy",
    "noiseavgenergy","noisesdenergy","noiseminenergy","noisemaxenergy","voicesumenergy",
    "voiceavgenergy","voicesdenergy","voiceminenergy","voicemaxenergy","silencesensedfraction","noisesensedfraction",
    "voicesensedfraction","unknownsensedfraction","silenceexpectedfraction","noiseexpectedfraction","voiceexpectedfraction",
    "unknownexpectedfraction","countconversation"]
                  PECORDING_MINUTES: 
                    type: integer
                  PAUSED_MINUTES:
                    type: integer
        additionalProperties: 
          $ref: "#/definitions/PROVIDER"
  
  PHONE_DATA_YIELD:
    type: object
    required: [SENSORS, PROVIDERS]
    properties:
      SENSORS:
        type: ["null", array]
        items:
          type: string
      PROVIDERS:
        type: ["null", object]
        properties:
          RAPIDS:
            allOf:
              - $ref: "#/definitions/PROVIDER"
              - properties:
                  FEATURES:
                    uniqueItems: True
                    items:
                      type: string
                      enum: [ratiovalidyieldedminutes, ratiovalidyieldedhours]
                  MINUTE_RATIO_THRESHOLD_FOR_VALID_YIELDED_HOURS:
                    type: number
                    minimum: 0
                    maximum: 1
        additionalProperties: 
          $ref: "#/definitions/PROVIDER"
                  


  PHONE_KEYBOARD:
    type: object
    required: [TABLE, PROVIDERS]
    properties:
      TABLE: 
        type: string
      PROVIDERS:
        type: ["null", object]
        additionalProperties: 
          $ref: "#/definitions/PROVIDER"

  PHONE_LIGHT:
    type: object
    required: [TABLE, PROVIDERS]
    properties:
      TABLE:
        type: string
      PROVIDERS:
        type: ["null", object]
        properties:
          RAPIDS:
            allOf:
              - $ref: "#/definitions/PROVIDER"
              - properties:
                  FEATURES:
                    uniqueItems: True
                    items:
                      type: string
                      enum: ["count", "maxlux", "minlux", "avglux", "medianlux", "stdlux"]
        additionalProperties: 
          $ref: "#/definitions/PROVIDER"

  PHONE_LOCATIONS:
    type: object
    required: [TABLE, LOCATIONS_TO_USE, FUSED_RESAMPLED_CONSECUTIVE_THRESHOLD, PROVIDERS]
    properties:
      TABLE: 
        type: string
      LOCATIONS_TO_USE:
        type: string
        enum: [ALL, GPS, ALL_RESAMPLED, FUSED_RESAMPLED]
      FUSED_RESAMPLED_CONSECUTIVE_THRESHOLD:
        type: integer
        exclusiveMinimum: 0
      FUSED_RESAMPLED_TIME_SINCE_VALID_LOCATION:
        type: integer
        exclusiveMinimum: 0
      PROVIDERS:
        type: ["null", object]
        properties:
          DORYAB:
            allOf:
                - $ref: "#/definitions/PROVIDER"
                - properties:
                    FEATURES: 
                      type: array
                      uniqueItems: True
                      items:
                        type: string
                        enum: [locationvariance,loglocationvariance,totaldistance,averagespeed,varspeed,circadianmovement,numberofsignificantplaces,numberlocationtransitions,radiusgyration,timeattop1location,timeattop2location,timeattop3location,movingtostaticratio,outlierstimepercent,maxlengthstayatclusters,minlengthstayatclusters,meanlengthstayatclusters,stdlengthstayatclusters,locationentropy,normalizedlocationentropy]
                    ACCURACY_LIMIT:
                      type: integer
                      exclusiveMinimum: 0
        additionalProperties:
          $ref: "#/definitions/PROVIDER"
    
  PHONE_MESSAGES:
    type: object
    required: [TABLE, PROVIDERS]
    properties: 
      TABLE: 
        type: string
      PROVIDERS:
        type: ["null", object]
        properties:
          RAPIDS:
            allOf:
              - $ref: "#/definitions/PROVIDER"
              - properties:
                  MESSAGES_TYPES:
                    type: array
                    uniqueItems: True
                    items:
                      type: string
                      enum: ["received", "sent"]
                  FEATURES:
                    type: object
                    required: [received, sent]
                    properties:
                      received:
                        type: array
                        uniqueItems: True
                        items:
                          type: string
                          enum: ["count", "distinctcontacts", "timefirstmessage", "timelastmessage", "countmostfrequentcontact"]
                      
                      sent:
                        type: array
                        uniqueItems: True
                        items:
                          type: string 
                          enum: ["count", "distinctcontacts", "timefirstmessage", "timelastmessage", "countmostfrequentcontact"]
    
  PHONE_SCREEN:
    type: object
    required: [TABLE, PROVIDERS]
    properties:
      TABLE: 
        type: string
      PROVIDERS:
        type: ["null", object]
        properties:
          RAPIDS:
            allOf:
              - $ref: "#/definitions/PROVIDER"
              - properties:
                  REFERENCE_HOUR_FIRST_USE: 
                    type: integer
                  IGNORE_EPISODES_SHORTER_THAN:
                    type: integer
                    minimum: 0
                  IGNORE_EPISODES_LONGER_THAN:
                    type: integer
                    minimum: 0
                  FEATURES:
                    uniqueItems: True
                    items:
                      type: string
                      enum: ["countepisode", "sumduration", "maxduration", "minduration", "avgduration", "stdduration", "firstuseafter"] 
                  EPISODE_TYPES:
                    type: array
                    uniqueItems: True
                    items:
                      type: string
                      enum: ["unlock"]

  PHONE_WIFI_CONNECTED:
    type: object
    required: [TABLE, PROVIDERS]
    properties:
      TABLE: 
        type: string
      PROVIDERS:
        type: ["null", object]
        properties:
          RAPIDS:
            allOf:
              - $ref: "#/definitions/PROVIDER"
              - properties:
                  FEATURES:
                    items:
                      type: string
                      enum: ["countscans", "uniquedevices", "countscansmostuniquedevice"]
        additionalProperties: 
          $ref: "#/definitions/PROVIDER"
  
  PHONE_WIFI_VISIBLE:
    type: object
    required: [TABLE, PROVIDERS]
    properties:
      TABLE:
        type: string
      PROVIDERS:
        type: ["null", object]
        properties:
          RAPIDS:
            allOf:
              - $ref: "#/definitions/PROVIDER"
        additionalProperties: 
          $ref: "#/definitions/PROVIDER"
                
                  













